### ISSUE TITLE
不指定高、宽则显示不了Child Widget？

### ISSUE THREAD

**Issue by bagualing** [Fliggy-Mobile/fdottedline#1]
在指定了Child Wideget，但没有指定FDottedLine的高或宽属性值时，显示不了？？

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: FDottedLine(
          color: Colors.amber,
          strokeWidth: 2.0,
          dottedLength: 8.0,
          space: 3.0,
          corner: FDottedLineCorner.all(6.0),

          /// add widget
          child: Container(
            color: Colors.blue[100],
            width: 130,
            height: 70,
            alignment: Alignment.center,
            child: Text("0873"),
          ),
        ),
      ),
    );
  }

> [✓] Flutter (Channel dev, 1.19.0-3.0.pre, on Microsoft Windows [Version 10.0.19041.264], locale zh-CN)
    • Flutter version 1.19.0-3.0.pre at C:\flutter
    • Framework revision 6135091de9 (7 days ago), 2020-06-01 17:17:03 -0700
    • Engine revision e39301f23f
    • Dart version 2.9.0 (build 2.9.0-13.0.dev 6489a0c68d)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

**Comment by chenBingX** [comment]
感谢反馈，在最新的 1.0.1 版本中已经修正了哦。
