### ISSUE TITLE
Could you fix your plugin to be compatible with flutter 3.0?

### ISSUE THREAD

**Issue by YowFung** [Fliggy-Mobile/fdottedline#4]
After I upgrade flutter SDK to 3.0, I can't run my app.
Could you provide a new version to add compatibility with flutter 3.0?

Related: https://github.com/flutter/flutter/issues/103571#issuecomment-1125694094

**Comment by Karthick47v2** [comment]
@YowFung Looks like repo owner is not available for long time. I have updated the plugin to be compatible with flutter 3.0.0. You can check it [here](https://github.com/Karthick47v2/fdottedline/tree/img-fix)

**Comment by YowFung** [comment]
很高兴看到作者已经更新版本了，感谢！
